### ISSUE TITLE
Shopping Items List

### ISSUE THREAD

**Issue by natush2** [natush2/shopping-buddy#1]
# Shopping Items List

## Value Proposition

**As a user**

**I want to** browse a well-organised list of shopping items,

**so that** I can easily see what I need to buy.

## Acceptance Criteria

- The homepage displays a list of shopping items.
- The shopping list is headlined with its purpose.
- Each item listing includes:
  - Shopping item name
  - Shopping item quantity
  - Shopping item category
- A counter displays the total number of items currently on the shopping list.
- Each category is visually differentiated, for example, by using different colours.
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [ ] Create feature branch `feature/shopping-items-list`
- [ ] Inspect and adapt the example data in the [assets folder](./assets/shopping-items.json)
  - [ ] Add an `imageUrl` for each shopping item, for example from [unsplash.com](unsplash.com). You first need the image in the User Story [Shopping Item Details](./shopping-item-details.md)

**Comment by natush2** [comment]
### Список товарів для покупок

**Ціннісна пропозиція**  
Як користувач,  
Я хочу переглядати добре організований список товарів для покупок,  
щоб я міг легко побачити, що мені потрібно купити.

**Опис**  
Capstone Student Todo: Додати wireframes

**Критерії приймання**  
- Головна сторінка відображає список товарів для покупок.
- Список покупок має заголовок, що вказує на його призначення.
- Кожен товар у списку включає:
  - Назву товару
  - Кількість товару
  - Категорію товару
- Лічильник відображає загальну кількість товарів у списку.
- Кожна категорія візуально відрізняється, наприклад, за допомогою різних кольорів.
- Список підтримує вертикальне прокручування для розміщення кількох записів.

**Завдання**  
- Створити гілку функціоналу `feature/shopping-items-list`.
- Перевірити та адаптувати приклад даних у папці assets.
- Додати `imageUrl` для кожного товару, наприклад, з unsplash.com. Спочатку потрібно отримати зображення для історії користувача "Деталі товару для покупок".

**Comment by JessicaLoers** [comment]
📒 Handout/Link List
[React with Arrays](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/react-with-arrays/react-with-arrays.md)
Knowing how to use .map() to render lists in JSX
Understanding how to render items from an array of objects
Knowing to add a unique key for list items
