### ISSUE TITLE
Create Shopping Item

### ISSUE THREAD

**Issue by natush2** [natush2/shopping-buddy#2]
# Create Shopping Item

## Value Proposition

**As a user**

**I want to** add new items to my shopping list,

**so that** I can keep track of what I need to buy.

## Description

Capstone Student Todo: Add wireframes

## Acceptance Criteria

- A form for adding shopping items is displayed at the top of the homepage.
- The form is headlined with its purpose.
- The form must include labelled fields for:
  - Shopping item name
  - Shopping item quantity
  - Shopping item category
  - Shopping item comment
- The following fields are mandatory:
  - Shopping item name
  - Shopping item quantity
  - Shopping item category
- The category is selected from the existing categories list via a dropdown menu.
- The categories dropdown must include a default option, "Please select a category", and necessitates a selection.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- Upon form submission, the new item is added to the top of the shopping list.

## Tasks

- [ ] Create feature branch `feature/create-shopping-item`
- [ ] The category options are listed in the [`categories.json`](./assets/categories.json) file
- [ ] Capstone Student Todo: Add tasks

> 💡 It is not yet possible to add images at this stage. For this reason, a placeholder image should be saved when creating a shopping item.

**Comment by JessicaLoers** [comment]
📒 Handout/Link List
[react-state-2: Handling Form Data](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/react-state-2/react-state-2.md#handling-form-data)
[react-state-3: Updating Arrays of Objects in State / adding a new object](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/react-state-3/react-state-3.md#adding-a-new-object)

**Comment by natush2** [comment]
**Створення товару для покупок**

**Пропозиція цінності**  
Як користувач,

Я хочу додати нові товари до мого списку покупок,

щоб я міг відслідковувати, що мені потрібно купити.

**Опис**  
Студент капстонного проєкту: Додати ескізи інтерфейсу

**Критерії приймання**  
- Форма для додавання товарів відображається в верхній частині домашньої сторінки.
- Форма має заголовок, що описує її призначення.
- Форма повинна містити позначені поля для:
  - Назви товару
  - Кількості товару
  - Категорії товару
  - Коментаря до товару
- Наступні поля є обов’язковими:
  - Назва товару
  - Кількість товару
  - Категорія товару
- Категорія вибирається з існуючого списку категорій через випадаюче меню.
- Випадаюче меню категорій повинно включати опцію за замовчуванням, "Будь ласка, виберіть категорію", і вимагати вибору.
- Надсилання форми з порожніми обов’язковими полями блокується, і чіткі повідомлення про помилки вказують на поля, які потрібно заповнити.
- Після надсилання форми новий товар додається на верхню частину списку покупок.

**Завдання**

- Створити гілку функціоналу `feature/create-shopping-item`
- Опції категорій перелічені у файлі `categories.json`
- Студент капстонного проєкту: Додати завдання
💡 На даному етапі ще не можливе додавання зображень. З цієї причини при створенні товару для покупок слід зберігати зображення-заповнювач.
